##################
# General Settings
##################

include:
  - project: 'drupal/gitlab-ci-templates'
    ref: 'main'
    file:
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  COMPOSER: composer.json
  COMPOSER_ROOT_VERSION: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}${CI_COMMIT_BRANCH}-dev"
  SIMPLE_TEST_BASE_URL: "http://127.0.0.1"
  BROWSERTEST_OUTPUT_DIRECTORY: "$CI_PROJECT_DIR/artifacts/test-results"

##################
# Stages
##################

stages:
  - 🏗️ Build
  - 🪄 Lint
  - 🧪 Test

##################
# Job Templates
##################

.default-job-settings: &default-job-settings
  interruptible: true
  allow_failure: false
  image: "docker.io/drupalci/php-8.2-apache:production"
  services:
    - mysql:8
  variables:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: root
  before_script:
    - composer install
    - ./vendor/bin/drush site:install standard --db-url=mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql/$MYSQL_DATABASE -y
    - ./vendor/bin/drush en webbage -y

.composer-cache: &composer-cache
  cache:
    key: composer-cache
    paths:
      - vendor/
    policy: pull-push

##################
# Jobs
##################

'📦️ Composer Install':
  <<: *default-job-settings
  stage: 🏗️ Build
  script:
    - composer validate
    - composer install
  artifacts:
    paths:
      - vendor/

'🧹 PHPCS (Coding Standards)':
  <<: *default-job-settings
  stage: 🪄 Lint
  script:
    - ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme .

'🧹 PHPStan (Static Analysis)':
  <<: *default-job-settings
  stage: 🪄 Lint
  script:
    - ./vendor/bin/phpstan analyze --configuration=phpstan.neon

'🧪 PHPUnit Tests':
  <<: *default-job-settings
  stage: 🧪 Test
  script:
    - ./vendor/bin/phpunit modules/custom/webbage/tests/src/Functional
  artifacts:
    when: always
    paths:
      - artifacts/test-results
    reports:
      junit: artifacts/test-results/junit.xml
