name: 'Web Blog - Default'
description: 'A recipe to manage default installed modules, configs and permissions.'
type: install
install:
  - path
  - text
  - node
  - user
  - menu_ui
  - content_moderation
  - media_library
  - manage_display
  - entityqueue
  - webdev
  - webassets
  - display_builder
  - display_builder_entity_view
  - display_builder_ui
config:
  strict: false
  import:
    display_builder:
      - display_builder.profile.default
